[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
dice_game = "BEv6mLWh28qF15i3CPChEoFgE746Z4Hz4yJdBAC3f759"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
